DROP TABLE CUSTOMER_T;
CREATE TABLE CUSTOMER_T (
    NO    NUMBER            NOT NULL PRIMARY KEY
  , ID    VARCHAR2(32 BYTE) NOT NULL UNIQUE
  , NAME  VARCHAR2(32 BYTE) NOT NULL
  , JOB   VARCHAR2(32 BYTE) NULL
  , PHONE CHAR(13 BYTE)     NULL UNIQUE
  , JUBUN CHAR(14 BYTE)     NULL UNIQUE
);